### ISSUE TITLE
update PAIRED_ENGLISH steps

### ISSUE THREAD

**Issue by jamesjun** [flatironinstitute/spikeforest_recordings#1]
1. Copy `paired_english` to paired_english_irc
2. Remove non-essential files in `paired_english`
3. Run `scripts\upload_english\upload_script.py`
4. Run `scripts\upload_english\patch_toplevel_index.py`
4a. Git push `spikeforest_recordings`
5. In spikeforest2, copy `working/runs/0214` to `0311`
6. Modify `001a_spec.json` and `001b_spec.json` (KiloSort1/2) and update `studysets.json` SHA1 from spikeforest_recordings\recordings\studysets.json file and add `PAIRED_ENGLISH` studyset
6a. Git push `spikeforest2`
7. Start a tmux session and run `./all.sh` and check on the [staging website](http://spike-front-staging.herokuapp.com/)
8. Push to the production website by running `website_upload/load_data_into_remote_database_prod.sh output.json`
9. Notify Dan English

**Comment by jamesjun** [comment]
Steps 1-3 done

**Comment by magland** [comment]
There's another step 4b: push changes created by scripts to spikeforest_recordings repo

**Comment by jamesjun** [comment]
will do!

**Comment by jamesjun** [comment]
steps 1-6 done, step 7 pending (TMUX session).

**Comment by jamesjun** [comment]
Done.
